/*
 * TIMER2_cfg.h
 *
 *  Created on: Mar 15, 2019
 *      Author: Muhammad.Elzeiny
 */

#ifndef TIMER2_CFG_H_
#define TIMER2_CFG_H_

/*
 * write number of steps to count in range [0-255]
 *
 * */
#define TIMER2_STEPS_COMPARED_VALUE					(u8)50
/*
 * choose between
 * TIMER2_MODE_NORMAL_MSK
 * TIMER2_MODE_CTC_MSK
 * TIMER2_MODE_FAST_PWM_MSK
 * TIMER2_MODE_PHASE_CORRECT_MSK
 *
 */
#define TIMER2_MODE_SELECTOR_MSK			TIMER2_MODE_FAST_PWM_MSK

/*
 * choose between
 *
 * TIMER2_PRESCALER_NO_MSK
 * TIMER2_PRESCALER_8_MSK
 * TIMER2_PRESCALER_64_MSK
 * TIMER2_PRESCALER_256_MSK
 * TIMER2_PRESCALER_1024_MSK
 *
 * */

#define TIMER2_PRESCALER_SELECTOR_MSK  TIMER2_PRESCALER_8_MSK
/*
 * Choose between
 *
 * TIMER2_OUTPUT_NONE_MSK
 * TIMER2_OUTPUT_TOGGLE_MSK
 * TIMER2_OUTPUT_SET_MSK
 * TIMER2_OUTPUT_CLEAR_MSK
 */

#define TIMER2_NON_PWM_OC2_PIN_OUTPUT_MSK		TIMER2_OUTPUT_TOGGLE_MSK

 /* Choose between
 * FAST_PWM_NONE_INVERTING_MODE_MSK
 * FAST_PWM_INVERTING_MODE_MSK
 * */
#define TIMER2_FAST_PWM_OC2_PIN_OUTPUT_MSK			FAST_PWM_NONE_INVERTING_MODE_MSK
/*
 * Choose between
 * PHASE_CORRECT_CLEAR_UP_COUNTING
 * PHASE_CORRECT_SET_UP_COUNTING

 */
#define TIMER2_PHASE_CORRECT_OC2_PIN_OUTPUT_MSK		PHASE_CORRECT_CLEAR_UP_COUNTING

#endif /* TIMER2_CFG_H_ */
