/*
 * DIO_cfg.h
 *
 *  Created on: Feb 16, 2019
 *      Author: Muhammad.Elzeiny
 */

#ifndef J7_LAB_SRC_MCAL_DIO_DIO_CFG_H_
#define J7_LAB_SRC_MCAL_DIO_DIO_CFG_H_

#define DIO_PIN_INPUT			0
#define DIO_PIN_OUTPUT			1

/*choose between DIO_PIN_INPUT / DIO_PIN_OUTPUT */
#define DIO_PIN_A0_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_A1_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_A2_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_A3_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_A4_DIR			DIO_PIN_INPUT
#define DIO_PIN_A5_DIR			DIO_PIN_INPUT
#define DIO_PIN_A6_DIR			DIO_PIN_INPUT
#define DIO_PIN_A7_DIR			DIO_PIN_INPUT

#define DIO_PIN_B0_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_B1_DIR			DIO_PIN_INPUT
#define DIO_PIN_B2_DIR			DIO_PIN_INPUT
#define DIO_PIN_B3_DIR			DIO_PIN_INPUT
#define DIO_PIN_B4_DIR			DIO_PIN_INPUT
#define DIO_PIN_B5_DIR			DIO_PIN_INPUT
#define DIO_PIN_B6_DIR			DIO_PIN_INPUT
#define DIO_PIN_B7_DIR			DIO_PIN_INPUT

#define DIO_PIN_C0_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_C1_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_C2_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_C3_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_C4_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_C5_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_C6_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_C7_DIR			DIO_PIN_OUTPUT

#define DIO_PIN_D0_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_D1_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_D2_DIR			DIO_PIN_OUTPUT
#define DIO_PIN_D3_DIR			DIO_PIN_INPUT
#define DIO_PIN_D4_DIR			DIO_PIN_INPUT
#define DIO_PIN_D5_DIR			DIO_PIN_INPUT
#define DIO_PIN_D6_DIR			DIO_PIN_INPUT
#define DIO_PIN_D7_DIR			DIO_PIN_OUTPUT

#endif /* J7_LAB_SRC_MCAL_DIO_DIO_CFG_H_ */
