/*
 * SCHEDULER_cfg.h
 *
 *  Created on: Mar 16, 2019
 *      Author: Muhammad.Elzeiny
 */

#ifndef J7_LAB_SRC_SCHEDULER_SCHEDULER_CFG_H_
#define J7_LAB_SRC_SCHEDULER_SCHEDULER_CFG_H_

#define SCHEDULER_MAX_NO_OF_TASKS				5
/*
 * SCHEDULER_MODE_DISABLE
 * SCHEDULER_MODE_TIMER_CTC
 * SCHEDULER_MODE_TIMER_NORMAL
 */
#define SCHEDULER_MODE_SELECTOR				SCHEDULER_MODE_TIMER_CTC
#endif /* J7_LAB_SRC_SCHEDULER_SCHEDULER_CFG_H_ */
