/*
 * EXTI_cfg.h
 *
 *  Created on: Mar 2, 2019
 *      Author: Muhammad.Elzeiny
 */

#ifndef J7_LAB_SRC_MCAL_EXTI_EXTI_CFG_H_
#define J7_LAB_SRC_MCAL_EXTI_EXTI_CFG_H_

/*
 * choose between
 * EXTI_EDGE_SELECTOR_RISING
 * EXTI_EDGE_SELECTOR_FALLING
 * EXTI_EDGE_SELECTOR_ONCHANGE
 */
#define EXTI_EDGE_SELECTOR_INT0			EXTI_EDGE_SELECTOR_RISING
#define EXTI_EDGE_SELECTOR_INT1			EXTI_EDGE_SELECTOR_ONCHANGE
#define EXTI_EDGE_SELECTOR_INT2			EXTI_EDGE_SELECTOR_RISING /*On Change not supported*/

#endif /* J7_LAB_SRC_MCAL_EXTI_EXTI_CFG_H_ */
